# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "psych", "~> 4.0"

group :development, :test do
  gem "bootsnap"
  gem "decidim"
  gem "letter_opener_web"
  gem "listen"
  gem "pry-rails"
end

gem "rubocop-factory_bot", "2.25.1"
