# frozen_string_literal: true

source "https://rubygems.org"

gemspec

# temporal solution while gems embrace new psych 4 (the default in Ruby 3.1) behavior.
gem "psych", "< 4"

group :development, :test do
  gem "bootsnap"
  gem "decidim"
  gem "letter_opener_web"
  gem "listen"
  gem "pry-rails"
end
